package models;
// Generated 02-mar-2021 20:28:41 by Hibernate Tools 4.3.1



/**
 * Vistaplantilla generated by hbm2java
 */
public class Vistaplantilla  implements java.io.Serializable {


     private VistaplantillaId id;

    public Vistaplantilla() {
    }

    public Vistaplantilla(VistaplantillaId id) {
       this.id = id;
    }
   
    public VistaplantillaId getId() {
        return this.id;
    }
    
    public void setId(VistaplantillaId id) {
        this.id = id;
    }




}


